package codegeneration;

import ast.Program;
import ast.Definition.Definition;
import ast.Definition.FuncionDefinition;
import ast.Definition.VarDefinition;
import ast.expressions.Expression;
import ast.statements.Asigment;
import ast.statements.IfStatement;
import ast.statements.Input;
import ast.statements.Print;
import ast.statements.Return;
import ast.statements.Statement;
import ast.statements.WhileStatement;
import ast.types.FuncionType;
import ast.types.VoidType;

public class ExecuteVisitor extends abstractCodeGeneratorVisitor {

	ValueVisitor vv;
	AddressVisitor av;

	public ExecuteVisitor(CodeGenerator c) {
		super(c);
		vv = new ValueVisitor(c);
		av = new AddressVisitor(c, vv);
		vv.setAv(av);
	}

	@Override
	public Object Visit(Program d, Object o) {

		this.cg.call("main");
		this.cg.halt();
		for (Definition def : d.definitions) {
			def.Accept(this, o);
		}
		return null;
	}

	@Override
	public Object Visit(FuncionDefinition d, Object o) {
		this.cg.AutoGeneratedLabel(d.getName());
		this.cg.line(d.getLine());
		// to allocate enough space on top of the stack for parameters
		this.cg.enter(d.getBytesParameters());

		for (VarDefinition def : ((FuncionType) d.getType()).getVars()) {
			def.Accept(this, o);
		}
		for (Statement def : d.getStatements()) {
			def.Accept(this, d);
		}

		if (((FuncionType) d.getType()).getReturnType() instanceof VoidType) {
			this.cg.Return(0, d.getBytesLocalVariables(), d.getBytesParameters());
		}
		return null;
	}

	@Override
	public Object Visit(VarDefinition d, Object o) {
		this.cg.line(d.getLine());
		this.cg.comment(d.getName() + ":" + d.getType().getClass().getName());
		return null;
	}

	@Override
	public Object Visit(Asigment d, Object o) {
		this.cg.line(d.getLine());
		this.cg.print("\t' * Assignment");
		d.ExpressionA.Accept(av, o);
		d.ExpressionB.Accept(vv, o);
		this.cg.store(d.ExpressionA.getType().getSuffix());
		return null;
	}

	@Override
	public Object Visit(IfStatement d, Object o) {
		this.cg.comment("If statement:");
		String Else = this.cg.AutoGeneratedLabel("else");
		String End = this.cg.AutoGeneratedLabel("end");
		d.getExpression().Accept(vv, o);
		this.cg.jumpIfZero(Else);
		for (Statement s : d.getBody()) {
			s.Accept(vv, o);
		}
		this.cg.jump(End);

		this.cg.label(Else);
		if (d.getElseBody() != null) {
			this.cg.comment("else body:");
			for (Statement s : d.getElseBody()) {
				s.Accept(vv, o);
			}
		}
		this.cg.label(End);
		return null;
	}

	@Override
	public Object Visit(WhileStatement d, Object o) {
		this.cg.comment("While statement:");
		String Start = this.cg.AutoGeneratedLabel("start");
		String End = this.cg.AutoGeneratedLabel("end");

		this.cg.label(Start);
		d.getExpression().Accept(vv, o);
		this.cg.jumpIfZero(End);
		for (Statement s : d.getBody()) {
			s.Accept(vv, o);
		}
		this.cg.jump(Start);
		this.cg.label(End);

		return null;
	}

	@Override
	public Object Visit(Input d, Object o) {

		this.cg.comment("Read");
		for (Expression def : d.getExp()) {
			def.Accept(av, null);
			this.cg.in(def.getType().getSuffix());
			this.cg.store(def.getType().getSuffix());
		}

		return null;
	}

	@Override
	public Object Visit(Print d, Object o) {

		this.cg.comment("Write");
		for (Expression def : d.getExp()) {
			def.Accept(vv, null);
			this.cg.out(def.getType().getSuffix());

		}
		return null;
	}

	@Override
	public Object Visit(Return d, Object o) {
		d.getExpression().Accept(vv, null);
		FuncionDefinition funDefinition = (FuncionDefinition) o;

		this.cg.Return(d.getExpression().getType().offsetSize(), funDefinition.getBytesLocalVariables(),
				funDefinition.getBytesParameters());

		return null;
	}

}
